#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

From docker.io/centos:@OS_VERSION@

@SET_PROXY@

RUN yum -y update && yum install -y \
git \
make \
gcc \
libseccomp \
chrony \
curl

# This will install the proper golang to build Kata components
@INSTALL_GO@
